services:
  - type: web
    name: stoke
    env: python
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd estoque_project && python manage.py collectstatic --no-input && python manage.py migrate --no-input && python manage.py create_superuser_if_none
    startCommand: cd estoque_project && gunicorn estoque_project.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@stoke.com
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: SETUP_KEY
        generateValue: true

