# Generated by Django 5.2.4 on 2025-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='eh_brinde',
            field=models.BooleanField(default=False, verbose_name='É Brinde'),
        ),
    ]
