# Generated by Django 5.2.4 on 2025-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_lote_preco_venda_produto_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('LOJA', 'Venda na Loja'), ('EXTERNA', 'Venda Externa')], default='LOJA', max_length=10),
        ),
    ]
