# Generated by Django 5.1.7 on 2025-10-10 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pedidocompra_itempedidocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoChegando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Compra')),
                ('data_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra')),
                ('data_prevista_chegada', models.DateField(blank=True, null=True, verbose_name='Previsão de Chegada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('incluido_estoque', models.BooleanField(default=False, verbose_name='Já Incluído no Estoque')),
                ('data_inclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Inclusão no Estoque')),
            ],
            options={
                'verbose_name': 'Produto Chegando',
                'verbose_name_plural': 'Produtos Chegando',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.RemoveField(
            model_name='pedidocompra',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='ItemPedidoCompra',
        ),
        migrations.DeleteModel(
            name='PedidoCompra',
        ),
    ]
