# Generated by Django 5.2.4 on 2025-08-22 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_venda_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='margem_lucro_ideal',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Define a margem de lucro desejada para os produtos. Isso será usado para destacar produtos com margens acima ou abaixo do ideal.', max_digits=5, verbose_name='Margem de Lucro Ideal (%)'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='limite_estoque_baixo',
            field=models.PositiveIntegerField(default=10, help_text='Notificar quando o estoque de um produto estiver abaixo deste valor.'),
        ),
    ]
