# Generated by Django 5.1.7 on 2025-10-10 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_produtochegando_remove_pedidocompra_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtochegando',
            name='produto_existente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_chegando', to='inventario.produto'),
        ),
    ]
