# Generated by Django 5.1.7 on 2025-10-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_produtochegando_produto_existente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtochegando',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_chegando', to='inventario.fornecedor'),
        ),
    ]
