# Generated by Django 5.2.4 on 2025-08-22 22:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_configuracao_margem_lucro_ideal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, help_text='O motivo da devolução.', null=True)),
                ('venda', models.ForeignKey(help_text='A venda original de onde os itens foram devolvidos.', on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='inventario.venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.devolucao')),
                ('item_venda_original', models.ForeignKey(help_text='O item da venda que está sendo devolvido.', on_delete=django.db.models.deletion.PROTECT, to='inventario.itemvenda')),
            ],
        ),
    ]
