# Generated by Django 5.2.7 on 2025-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_produtochegando_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_produto_parado',
            field=models.PositiveIntegerField(default=60, help_text='Produtos sem vendas neste período serão listados como parados', verbose_name='Dias sem vender para considerar parado'),
        ),
    ]
