# Generated by Django 5.2.7 on 2025-10-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_configuracao_dias_produto_parado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdevolucao',
            name='data_retorno_estoque',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de retorno ao estoque'),
        ),
        migrations.AddField(
            model_name='itemdevolucao',
            name='devolvido_ao_estoque',
            field=models.BooleanField(default=False, verbose_name='Devolvido ao estoque'),
        ),
    ]
