# Generated by Django 5.2.7 on 2025-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_itemdevolucao_data_retorno_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='recebida',
            field=models.BooleanField(default=False, help_text='Indica se o valor da venda já foi recebido', verbose_name='Recebida'),
        ),
    ]
