# Generated by Django 5.2.7 on 2025-10-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_venda_data_recebimento_venda_recebida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='recebida',
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventario.fornecedor'),
        ),
    ]
