# Generated by Django 5.2.7 on 2025-10-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_venda_data_recebimento_remove_venda_recebida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dias_cobertura_minima',
            field=models.PositiveIntegerField(default=15, help_text='Quantidade mínima de dias que o estoque deve cobrir', verbose_name='Dias de Cobertura Mínima'),
        ),
        migrations.AddField(
            model_name='produto',
            name='lead_time_dias',
            field=models.PositiveIntegerField(default=7, help_text='Tempo de entrega do fornecedor em dias', verbose_name='Lead Time (dias)'),
        ),
    ]
