# Generated by Django 5.2.7 on 2025-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_produto_dias_cobertura_minima_produto_lead_time_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_analise_tendencias',
            field=models.PositiveIntegerField(default=90, help_text='Quantidade de dias de histórico usado para análise de tendências e previsão de estoque', verbose_name='Período de Análise de Tendências (dias)'),
        ),
    ]
