# Generated by Django 5.2.7 on 2025-10-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_configuracao_dias_analise_tendencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVendaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_retirada', models.PositiveIntegerField()),
                ('preco_compra_lote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_utilizados', to='inventario.itemvenda')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.lote')),
            ],
            options={
                'verbose_name': 'Lote Utilizado em Venda',
                'verbose_name_plural': 'Lotes Utilizados em Vendas',
            },
        ),
    ]
