# Generated by Django 5.2.7 on 2025-10-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_itemvendalote'),
    ]

    operations = [
        # Índice para otimizar busca de itens vendidos por produto e venda
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(
                fields=['produto', 'venda'], 
                name='idx_itemvenda_prod_venda'
            ),
        ),
        # Índice para otimizar listagem de vendas por data e status
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(
                fields=['-data', 'status'], 
                name='idx_venda_data_status'
            ),
        ),
        # Índice para otimizar busca FIFO de lotes por produto
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(
                fields=['produto', 'data_entrada'], 
                name='idx_lote_prod_data'
            ),
        ),
        # Índice para quantidade atual de lotes
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(
                fields=['quantidade_atual'], 
                name='idx_lote_qtd_atual'
            ),
        ),
        # Índice para otimizar contagem de produtos chegando
        migrations.AddIndex(
            model_name='produtochegando',
            index=models.Index(
                fields=['produto_existente', 'incluido_estoque'], 
                name='idx_prodcheg_prod_incl'
            ),
        ),
    ]
