# Generated by Django 5.2.7 on 2025-10-24 16:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='itemvenda',
            name='idx_itemvenda_prod_venda',
        ),
        migrations.RemoveIndex(
            model_name='lote',
            name='idx_lote_prod_data',
        ),
        migrations.RemoveIndex(
            model_name='lote',
            name='idx_lote_qtd_atual',
        ),
        migrations.RemoveIndex(
            model_name='produtochegando',
            name='idx_prodcheg_prod_incl',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='idx_venda_data_status',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_10x',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5, verbose_name='Juros 10x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_11x',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Juros 11x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_12x',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5, verbose_name='Juros 12x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_2x',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), max_digits=5, verbose_name='Juros 2x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_3x',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5, verbose_name='Juros 3x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_4x',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=5, verbose_name='Juros 4x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_5x',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Juros 5x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_6x',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.50'), max_digits=5, verbose_name='Juros 6x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_7x',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5, verbose_name='Juros 7x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_8x',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.50'), max_digits=5, verbose_name='Juros 8x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='juros_9x',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5, verbose_name='Juros 9x (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='taxa_credito_avista',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Taxa cobrada em pagamentos no crédito em 1x', max_digits=5, verbose_name='Taxa de Crédito à Vista (%)'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='taxa_debito',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Taxa cobrada em pagamentos no débito', max_digits=5, verbose_name='Taxa de Débito (%)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='venda',
            name='taxa_aplicada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taxa Aplicada (%)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], default='DINHEIRO', max_length=10, verbose_name='Tipo de Pagamento'),
        ),
    ]
